# Generated by Django 3.1.5 on 2021-02-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_wanted_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='plat',
            field=models.ManyToManyField(to='blog.Plat'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='host',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='ドメイン'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_url', models.CharField(max_length=100, verbose_name='オファーurl')),
                ('posted', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('offer_mess', models.TextField(max_length=400, verbose_name='メッセージ')),
                ('wanted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.wanted')),
            ],
        ),
    ]
