# Generated by Django 3.1.5 on 2021-02-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210203_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='wanted/', verbose_name='画像'),
        ),
    ]
