# Generated by Django 3.1.5 on 2021-02-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210203_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='id',
            field=models.SlugField(default='000000', max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
