# Generated by Django 3.1.5 on 2021-02-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210203_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='id',
            field=models.SlugField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
