# Generated by Django 3.1.5 on 2021-03-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_by_official',
            field=models.BooleanField(default=False, verbose_name='公式からのオファー'),
        ),
        migrations.CreateModel(
            name='Recomend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_url', models.CharField(max_length=100, verbose_name='offer url')),
                ('posted', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('is_noticed', models.BooleanField(default=False, verbose_name='通知済み')),
                ('wanted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.wanted')),
            ],
        ),
    ]
