# Generated by Django 3.1.5 on 2021-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210305_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='how_good',
            field=models.CharField(choices=[('5', 'いい！'), ('3', 'まあまあ'), ('1', 'ちょっと違う')], default='2', max_length=2, verbose_name='フィット感'),
        ),
        migrations.AddField(
            model_name='wanted',
            name='is_accept_official',
            field=models.BooleanField(default=True, verbose_name='公式からのオファーを受け取りますか？'),
        ),
        migrations.DeleteModel(
            name='Recomend',
        ),
    ]
