# Generated by Django 3.1.5 on 2021-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210306_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='how_good',
            field=models.CharField(blank=True, choices=[('5', 'いい！'), ('3', 'まあまあ'), ('1', 'ちょっと違う')], max_length=2, null=True, verbose_name='フィット感'),
        ),
    ]
