# Generated by Django 3.1.5 on 2021-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210306_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_noticed',
            field=models.BooleanField(default=False, verbose_name='通知済み'),
        ),
    ]
