# Generated by Django 3.1.5 on 2021-02-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count',
        ),
    ]
